// src/App.tsx
import React from 'react';
import logo from './logo.svg';
import './App.css';
import { TabController } from './components/TabController';

function App() {
  return (
    <div className="App">
      <TabController
        props={[{
          statemet:'ola',
          btn_text: 'bt1'
        },
        {
          statemet:'ola 2',
          btn_text: 'bt2'
        },]
      }
      ></TabController>
    </div>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import TabController from "./components/TabController.vue";
</script>

<template>
  <TabController
    :props=" [
      {
       statement: 'asdasfdf',
       btn_text: 'ola'
      },
      {
       statement: 'asaaaaaadf',
       btn_text: 'ola'
      },
      {
       statement: 'asdfffffffffffffff',
       btn_text: 'ola'
      },
      ]"
  ></TabController>
</template>
